baseURL = "/"
languageCode = "en-us"
title = "konpig"
theme = "m10c"

[params]
 author = "Kim Youlim"
 description = "Welcome to my blog"
 
 [[params.social]]
 name = "github"
 url = "https://github.com/kimkonpig"
