baseURL = "/"
languageCode = "en-us"
title = "KONPIG BLOG"
theme = "m10c"
disqusShortname = "kimkonpig"

[params]
 author = "Kim Youlim"
 description = "Welcome"
 
 [[params.social]]
  name = "github"
  url = "https://github.com/kimkonpig"
 [[param.social]]
  name = "naver"
  url = "https://blog.naver.com/kon_pig"
